version: '3.3'

services:
  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: