"""empty message

Revision ID: 0ee2280107a7
Revises: 22e2f5231861
Create Date: 2025-07-09 10:37:15.576453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee2280107a7'
down_revision: Union[str, Sequence[str], None] = '22e2f5231861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chosen_character', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'characters', ['chosen_character'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'chosen_character')
    # ### end Alembic commands ###
