"""empty message

Revision ID: 10b7b0c633a5
Revises: 52f0ea078e05
Create Date: 2025-07-09 12:31:03.722684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10b7b0c633a5'
down_revision: Union[str, Sequence[str], None] = '52f0ea078e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'avatar_url',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=220),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'avatar_url',
               existing_type=sa.String(length=220),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
