"""empty message

Revision ID: a29775a8ce13
Revises: 10b7b0c633a5
Create Date: 2025-07-11 12:15:43.076638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a29775a8ce13'
down_revision: Union[str, Sequence[str], None] = '10b7b0c633a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_generated', sa.Boolean(), nullable=False))
    op.add_column('characters', sa.Column('avatar_img_url', sa.String(length=220), nullable=True))
    op.add_column('characters', sa.Column('system_prompt', sa.Text(), nullable=False))
    op.add_column('characters', sa.Column('init_message', sa.Text(), nullable=False))
    op.drop_column('characters', 'sex')
    op.drop_column('characters', 'abilities')
    op.drop_column('characters', 'places')
    op.drop_column('characters', 'avatar_url')
    op.drop_column('characters', 'additional_details')
    op.drop_column('characters', 'interests')
    op.drop_column('characters', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('additional_details', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('avatar_url', sa.VARCHAR(length=220), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('places', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('sex', postgresql.ENUM('male', 'female', name='sexenum'), autoincrement=False, nullable=False))
    op.drop_column('characters', 'init_message')
    op.drop_column('characters', 'system_prompt')
    op.drop_column('characters', 'avatar_img_url')
    op.drop_column('characters', 'is_generated')
    # ### end Alembic commands ###
